name: Next.js action 01 


on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 'lts-alpine'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js Application
        run: npm run build


